global using System.Diagnostics;
global using System.Drawing;
global using System.Drawing.Drawing2D;
global using System.Drawing.Imaging;
global using System.Globalization;
global using System.IO;
global using System.Net.Http;
global using System.Net.Http.Headers;
global using System.Runtime.InteropServices;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Nodes;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Windows.Automation;
global using static RDPilotApplication.ArtifactAnalysisService;
global using static RDPilotApplication.ArtifactStorageService;
global using static RDPilotApplication.ConfigurationService;
global using static RDPilotApplication.ControlLoopService;
global using static RDPilotApplication.DesktopConsoleService;
global using static RDPilotApplication.DesktopInputService;
global using static RDPilotApplication.ImageComparisonService;
global using static RDPilotApplication.LoopReplayService;
global using static RDPilotApplication.OpenAiResponsesService;
global using static RDPilotApplication.PromptAndRequestFactory;
global using static RDPilotApplication.QuestionAnswerService;
global using static RDPilotApplication.RecoveryMemoryService;
global using static RDPilotApplication.RunMetrics;
global using static RDPilotApplication.ScreenshotService;
global using static RDPilotApplication.UiAutomationService;
